import Head from "next/head";
import SearchResult from "../components/organisms/SearchResult";

export default function Find() {
  return (
    <>
      <Head>
        <title>Meet Up | チーム検索結果</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchResult />
    </>
  );
}
