import { useState } from "react";
import Head from "next/head";
import { Container } from "react-bootstrap";
import TeamProfile from "../components/organisms/TeamProfile";
import { Team } from "../type/team";
import teamApi from "../lib/teamApi";
import { useEffect } from "react";

export default function Index() {
  const [teams, setTeams] = useState([]);
  var setupPrepared = false;
  useEffect(() => {
    if (!setupPrepared) {
      teamApi.getTeamsLatest()?.then((res: any) => {
        console.log(res.data);
        setTeams(res.data);
      });
    }
    setupPrepared = true;
  }, []);
  return (
    <div>
      <Head>
        <title>Meet Up | ホーム</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <section>
          <h4 className="my-3">新着 メンバー募集チーム</h4>
          {teams.map((team: any) => {
            return <TeamProfile team={team} key={team.teamId} />;
          })}
        </section>
      </Container>
    </div>
  );
}
