import Head from "next/head";
import SigninForm from "../components/organisms/SigninForm";

export default function Signin() {
  return (
    <>
      <Head>
        <title>Meet Up | ログイン</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SigninForm />
    </>
  );
}
