import Head from "next/head";
import SignupForm from "../components/organisms/SignupForm";

export default function Signup() {
  return (
    <>
      <Head>
        <title>Meet Up | アカウント新規作成</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SignupForm />
    </>
  );
}
